workflows:
  ios-flutter-workflow:
    name: iOS Flutter Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build Flutter iOS release (un-signed)
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log